### ISSUE TITLE
Install not finding sql-file

### ISSUE THREAD

**Issue by MichaTausKamR** [PrivateDonut/TinyCMS#4]
I put up all files in the doc root and started it. Filled all the fields and then I just see an error that it can't find the sql-file necessary:

Installation failed: SQL file not found: /var/www/html/YXYX/install/functions/../SQL/website.sql

**Comment by PrivateDonut** [comment]
This is a current known bug with the current state of the CMS, but I will be pushing out a fix soon to fix a few known bugs
